version: '3.1'
services:
  database:
    image: postgres
    restart: always
    ports:
      - "5455:5432"
    environment:
      - POSTGRES_USER=mostafa
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postgresDB 
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./database_entry:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - database

  frontend:
    build: ./frontend/bitnine
    ports:
      - "8080:80"
